export const SET_CLASS = 'CLASSREVIEW::SET_CLASS';
export const RESET = 'CLASSREVIEW::RESET';
export const LOADING = 'CLASSREVIEW::LOADING';
export const RECEIVED = 'CLASSREVIEW::RECEIVE';
export const FINISH_SUCCESS = 'CLASSREVIEW::FINISH_SUCCESS';
export const ERROR = 'CLASSREVIEW::ERROR';
export const HIDE_LOADER = 'CLASSREVIEW::HIDE_LOADER';