export const RESET = 'RESETPASSWORD::RESET';
export const LOADING = 'RESETPASSWORD::LOADING';
export const RECEIVED = 'RESETPASSWORD::RECEIVE';
export const TOKENRECEIVED = 'RESETPASSWORD::TOKENRECEIVE';
export const ERROR = 'RESETPASSWORD::ERROR';
export const UPDATE_PROPERTY = 'RESETPASSWORD::UPDATE_PROPERTY';