export const RESET = 'PASSWORDRECOVERY::RESET';
export const LOADING = 'PASSWORDRECOVERY::LOADING';
export const RECEIVED = 'PASSWORDRECOVERY::RECEIVE';
export const ERROR = 'PASSWORDRECOVERY::ERROR';
export const UPDATE_PROPERTY = 'PASSWORDRECOVERY::UPDATE_PROPERTY';